/* The native image element is intentional here so the examples demonstrate the primitive with arbitrary image sources. */
/* eslint-disable @next/next/no-img-element */
import { Play, Quote, Star } from "lucide-react";
import { AspectRatio } from "@/components/ui/AspectRatio";

const imageSrc = "/aspect-ratio-art.svg";

export function VideoRatio() { return <AspectRatio ratio={16 / 9} className="rounded-lg bg-neutral-900"><div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-neutral-800 via-neutral-900 to-black"><div className="flex size-12 items-center justify-center rounded-full bg-white text-black"><Play className="ml-0.5 size-5 fill-current" /></div><span className="absolute bottom-3 left-3 text-xs text-neutral-400">16:9 video placeholder</span></div></AspectRatio>; }
export function SquareContent() { return <AspectRatio ratio={1} className="rounded-lg border border-neutral-200 bg-neutral-50 p-5 dark:border-neutral-800 dark:bg-neutral-950"><div className="flex h-full flex-col justify-between"><span className="text-xs uppercase tracking-[0.16em] text-neutral-500">No image needed</span><div><h3 className="text-xl font-semibold">A square content block</h3><p className="mt-2 text-sm text-neutral-500">Aspect ratio also works with text, controls, and any other content.</p></div></div></AspectRatio>; }
export function LandscapeImage() { return <AspectRatio ratio={16 / 9} className="rounded-lg"><img src={imageSrc} alt="Abstract landscape artwork" className="size-full object-cover" /></AspectRatio>; }
export function PortraitImage() { return <AspectRatio ratio={3 / 4} className="max-w-xs rounded-lg"><img src={imageSrc} alt="Abstract portrait artwork" className="size-full object-cover" /><span className="absolute bottom-3 left-3 rounded-full bg-black/70 px-3 py-1 text-xs text-white">Portrait · 3:4</span></AspectRatio>; }
export function BannerRatio() { return <AspectRatio ratio={21 / 9} className="rounded-lg bg-neutral-900"><img src={imageSrc} alt="Abstract banner artwork" className="size-full object-cover opacity-60 grayscale" /><div className="absolute inset-0 flex items-center px-6"><div><p className="text-xs uppercase tracking-[0.2em] text-neutral-300">Wide format</p><h3 className="mt-2 text-2xl font-semibold text-white">Build with proportion</h3></div></div></AspectRatio>; }
export function AvatarRatio() { return <AspectRatio ratio={1} className="size-24 rounded-full bg-neutral-200 dark:bg-neutral-800"><img src={imageSrc} alt="Abstract avatar artwork" className="size-full object-cover grayscale" /></AspectRatio>; }
export function ContainedImage() { return <AspectRatio ratio={4 / 3} className="rounded-lg border border-neutral-200 bg-neutral-100 p-6 dark:border-neutral-800 dark:bg-neutral-900"><img src={imageSrc} alt="Abstract artwork contained inside a frame" className="size-full object-contain" /></AspectRatio>; }
export function ResponsiveGallery() { return <div className="grid w-full grid-cols-2 gap-2"><AspectRatio ratio={1} className="rounded-md bg-neutral-200 dark:bg-neutral-800"><img src={imageSrc} alt="Gallery artwork one" className="size-full object-cover" /></AspectRatio><AspectRatio ratio={1} className="rounded-md bg-neutral-900"><div className="flex h-full items-center justify-center text-white"><Quote className="size-8" /></div></AspectRatio><AspectRatio ratio={1} className="rounded-md bg-neutral-100 p-4 dark:bg-neutral-900"><div className="flex h-full flex-col justify-end"><Star className="size-5 fill-current" /><p className="mt-2 text-xs">Always aligned.</p></div></AspectRatio><AspectRatio ratio={1} className="rounded-md bg-neutral-700"><img src={imageSrc} alt="Gallery artwork two" className="size-full object-cover opacity-70" /></AspectRatio></div>; }
export function ProductRatio() { return <div className="w-full max-w-sm rounded-lg border border-neutral-200 p-3 dark:border-neutral-800"><AspectRatio ratio={4 / 5} className="rounded-md bg-neutral-100 dark:bg-neutral-900"><img src={imageSrc} alt="Product artwork" className="size-full object-cover" /></AspectRatio><div className="flex items-center justify-between px-1 pt-3"><div><h3 className="font-medium">Studio object</h3><p className="text-sm text-neutral-500">$84.00</p></div><span className="text-xs text-neutral-500">4:5</span></div></div>; }
export function CustomRatio() { return <AspectRatio ratio={2 / 1} className="rounded-lg border border-dashed border-neutral-300 bg-neutral-50 dark:border-neutral-700 dark:bg-neutral-950"><div className="flex h-full items-center justify-center text-center"><div><p className="text-3xl font-semibold">2:1</p><p className="mt-1 text-sm text-neutral-500">Custom ratio</p></div></div></AspectRatio>; }
