"use client";
import { AlertTriangle, LogOut, RotateCcw, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/AlertDialog";
function AlertExample({ title, description, action, icon }: { title: string; description: string; action: string; icon: React.ReactNode }) { return <AlertDialog><AlertDialogTrigger asChild><Button variant="outline">{icon}{action}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel asChild><Button variant="outline">Cancel</Button></AlertDialogCancel><AlertDialogAction asChild><Button variant={action === "Delete" ? "destructive" : "primary"}>{action}</Button></AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
export function DeleteAlert() { return <AlertExample title="Delete project?" description="This permanently deletes the project and all of its data. This action cannot be undone." action="Delete" icon={<Trash2 className="size-4" />} />; }
export function UnsavedAlert() { return <AlertExample title="Discard unsaved changes?" description="You have changes that have not been saved. Are you sure you want to leave?" action="Discard" icon={<AlertTriangle className="size-4" />} />; }
export function LogoutAlert() { return <AlertExample title="Log out of this device?" description="You will need to sign in again to access your workspace." action="Log out" icon={<LogOut className="size-4" />} />; }
export function ResetAlert() { return <AlertExample title="Reset preferences?" description="All appearance and notification preferences will return to their defaults." action="Reset" icon={<RotateCcw className="size-4" />} />; }
export function ConfirmAlert() { return <AlertExample title="Publish changes?" description="Your latest changes will be visible to everyone with access to this project." action="Publish" icon={null} />; }
