import type { Metadata } from "next";

import { ThemeProvider } from "@/providers/ThemeProvider";
import Navbar from "@/components/Navbar";
import { outfit } from "@/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Joy UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className} antialiased bg-white dark:bg-black`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Navbar />

          {children}

          <footer className="p-4 bg-white dark:bg-black border-t border-gray-200 dark:border-neutral-700 text-center">
            <p className="text-sm text-gray-600 dark:text-gray-300">© 2025 Joy UI. All rights reserved.</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
