import type { Metadata } from "next";

import { ThemeProvider } from "@/providers/ThemeProvider";
import Navbar from "@/components/shared/Navbar";
import { outfit } from "@/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Joy UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className} antialiased bg-white text-neutral-900 dark:bg-black dark:text-white`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Navbar />

          {children}

          <footer className="border-t border-gray-200 bg-white p-4 text-center dark:border-neutral-700 dark:bg-black">
            <p className="text-sm text-gray-600 dark:text-gray-300">© 2025 Joy UI. All rights reserved.</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
