"use client";

import * as React from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { Checkbox } from "@/components/ui/Checkbox";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/Label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/RadioGroup";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";
import { Form, FormControl, FormDescription, FormField, FormLabel, FormMessage, FormSubmit } from "@/components/ui/Form";

export function BasicForm() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="email"><FormLabel>Email</FormLabel><FormControl type="email" placeholder="you@example.com" required /><FormMessage match="valueMissing">Please enter your email.</FormMessage></FormField><FormSubmit>Continue</FormSubmit></Form>; }
export function FormWithValidation() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="username"><FormLabel>Username</FormLabel><FormControl pattern="^[a-zA-Z0-9_]+$" required placeholder="joy_ui" /><FormDescription>Letters, numbers, and underscores only.</FormDescription><FormMessage match="valueMissing">A username is required.</FormMessage><FormMessage match="patternMismatch">Use only letters, numbers, and underscores.</FormMessage></FormField><FormSubmit>Save username</FormSubmit></Form>; }
export function FormWithLabel() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="project"><FormLabel>Project name</FormLabel><FormControl placeholder="Joy UI" /><FormDescription>This name will be visible to your team.</FormDescription></FormField><FormSubmit>Create project</FormSubmit></Form>; }
export function FormWithMultipleFields() { return <Form className="w-full max-w-sm space-y-4" onSubmit={(event) => event.preventDefault()}><FormField name="firstName"><FormLabel>First name</FormLabel><FormControl placeholder="Joy" required /></FormField><FormField name="role"><FormLabel>Role</FormLabel><FormControl placeholder="Product designer" required /></FormField><FormSubmit>Update profile</FormSubmit></Form>; }
export function FormWithCustomMessage() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="invite"><FormLabel>Invite code</FormLabel><FormControl placeholder="TEAM-2026" required minLength={8} /><FormMessage match="valueMissing">Invite code is required.</FormMessage><FormMessage match="tooShort">Your invite code is too short.</FormMessage></FormField><FormSubmit>Join workspace</FormSubmit></Form>; }
export function FormWithServerError() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="account" serverInvalid><FormLabel>Account email</FormLabel><FormControl type="email" defaultValue="taken@example.com" /><FormMessage match="valid" forceMatch>That account is already connected to another workspace.</FormMessage></FormField><FormSubmit>Connect account</FormSubmit></Form>; }

export function SignInForm() { return <Form className="w-full max-w-sm space-y-4" onSubmit={(event) => { event.preventDefault(); }}><FormField name="email"><FormLabel>Email</FormLabel><FormControl type="email" placeholder="you@example.com" required /><FormMessage match="valueMissing">Email is required.</FormMessage></FormField><FormField name="password"><FormLabel>Password</FormLabel><FormControl type="password" placeholder="••••••••" minLength={6} required /><FormMessage match="tooShort">Password must be at least 6 characters.</FormMessage></FormField><FormSubmit>Sign in</FormSubmit></Form>; }

const profileSchema = z.object({ name: z.string().min(2, "Enter at least 2 characters"), role: z.string().min(1, "Choose a role"), experience: z.enum(["junior", "mid", "senior"]), updates: z.boolean() });
type ProfileValues = z.infer<typeof profileSchema>;

export function ProfileCreationForm() { const [role, setRole] = React.useState(""); const [experience, setExperience] = React.useState("mid"); const [updates, setUpdates] = React.useState(true); return <Form className="w-full max-w-sm space-y-4" onSubmit={(event) => { event.preventDefault(); }}><FormField name="name"><FormLabel>Full name</FormLabel><FormControl placeholder="Joy Brar" required minLength={2} /><FormMessage match="valueMissing">Your name is required.</FormMessage></FormField><div><Label htmlFor="profile-role">Role</Label><Select value={role} onValueChange={setRole}><SelectTrigger id="profile-role" className="mt-2 w-full"><SelectValue placeholder="Select your role" /></SelectTrigger><SelectContent><SelectItem value="designer">Designer</SelectItem><SelectItem value="engineer">Engineer</SelectItem><SelectItem value="founder">Founder</SelectItem></SelectContent></Select></div><div><Label>Experience</Label><RadioGroup value={experience} onValueChange={setExperience} className="mt-2"><label className="flex items-center gap-2 text-sm"><RadioGroupItem value="junior" />Junior</label><label className="flex items-center gap-2 text-sm"><RadioGroupItem value="mid" />Mid-level</label><label className="flex items-center gap-2 text-sm"><RadioGroupItem value="senior" />Senior</label></RadioGroup></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={updates} onCheckedChange={(value) => setUpdates(value === true)} />Send product updates</label><FormSubmit>Create profile</FormSubmit></Form>; }

const signInSchema = z.object({ email: z.string().min(1, "Email is required").email("Enter a valid email"), password: z.string().min(6, "Password must be at least 6 characters") });
type SignInValues = z.infer<typeof signInSchema>;
export function SignInWithReactHookForm() { const { register, handleSubmit, formState: { errors } } = useForm<SignInValues>({ resolver: zodResolver(signInSchema), mode: "onBlur" }); return <form className="w-full max-w-sm space-y-4" onSubmit={handleSubmit(() => undefined)}><Input label="Email" type="email" placeholder="you@example.com" error={errors.email?.message} {...register("email")} /><Input label="Password" type="password" placeholder="••••••••" error={errors.password?.message} {...register("password")} /><Button type="submit">Sign in</Button></form>; }

export function ProfileWithReactHookForm() { const { register, control, handleSubmit, formState: { errors } } = useForm<ProfileValues>({ resolver: zodResolver(profileSchema), defaultValues: { role: "", experience: "mid", updates: true }, mode: "onBlur" }); return <form className="w-full max-w-sm space-y-4" onSubmit={handleSubmit(() => undefined)}><Input label="Full name" placeholder="Joy Brar" error={errors.name?.message} {...register("name")} /><div><label className="text-sm font-medium">Role</label><Controller name="role" control={control} render={({ field }) => <Select value={field.value} onValueChange={field.onChange}><SelectTrigger className="mt-2 w-full"><SelectValue placeholder="Select your role" /></SelectTrigger><SelectContent><SelectItem value="designer">Designer</SelectItem><SelectItem value="engineer">Engineer</SelectItem><SelectItem value="founder">Founder</SelectItem></SelectContent></Select>} />{errors.role && <p className="mt-1 text-sm text-red-500">{errors.role.message}</p>}</div><div><p className="text-sm font-medium">Experience</p><Controller name="experience" control={control} render={({ field }) => <RadioGroup value={field.value} onValueChange={field.onChange} className="mt-2"><label className="flex items-center gap-2 text-sm"><RadioGroupItem value="junior" />Junior</label><label className="flex items-center gap-2 text-sm"><RadioGroupItem value="mid" />Mid-level</label><label className="flex items-center gap-2 text-sm"><RadioGroupItem value="senior" />Senior</label></RadioGroup>} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("updates")} />Send product updates</label><Button type="submit">Create profile</Button></form>; }

export function PreferencesForm() { const [theme, setTheme] = React.useState("system"); return <Form className="w-full max-w-sm space-y-4" onSubmit={(event) => event.preventDefault()}><FormField name="workspace"><FormLabel>Workspace name</FormLabel><FormControl defaultValue="Joy UI" required /></FormField><div><Label htmlFor="theme-select">Theme</Label><Select value={theme} onValueChange={setTheme}><SelectTrigger id="theme-select" className="mt-2 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="system">System</SelectItem><SelectItem value="light">Light</SelectItem><SelectItem value="dark">Dark</SelectItem></SelectContent></Select><FormDescription>Choose how the workspace appears to you.</FormDescription></div><FormSubmit>Save preferences</FormSubmit></Form>; }

export function InviteWithReactHookForm() { const inviteSchema = z.object({ email: z.string().email("Enter a valid email"), access: z.enum(["viewer", "editor"]) }); const { register, handleSubmit, formState: { errors } } = useForm<{ email: string; access: "viewer" | "editor" }>({ resolver: zodResolver(inviteSchema), defaultValues: { access: "viewer" } }); return <form className="w-full max-w-sm space-y-4" onSubmit={handleSubmit(() => undefined)}><Input label="Teammate email" type="email" placeholder="teammate@example.com" error={errors.email?.message} {...register("email")} /><div><label className="text-sm font-medium">Access</label><select className="mt-2 h-10 w-full rounded-md border border-neutral-300 bg-white px-3 text-sm dark:border-neutral-700 dark:bg-neutral-950 dark:text-white" {...register("access")}><option value="viewer">Viewer</option><option value="editor">Editor</option></select></div><Button type="submit">Send invite</Button></form>; }

export function ContactWithReactHookForm() { const contactSchema = z.object({ name: z.string().min(2, "Enter your name"), email: z.string().email("Enter a valid email"), message: z.string().min(20, "Message must be at least 20 characters") }); const { register, handleSubmit, formState: { errors } } = useForm<{ name: string; email: string; message: string }>({ resolver: zodResolver(contactSchema), mode: "onBlur" }); return <form className="w-full max-w-sm space-y-4" onSubmit={handleSubmit(() => undefined)}><Input label="Name" placeholder="Joy Brar" error={errors.name?.message} {...register("name")} /><Input label="Email" type="email" placeholder="you@example.com" error={errors.email?.message} {...register("email")} /><Textarea label="Message" placeholder="Tell us how we can help" error={errors.message?.message} {...register("message")} /><Button type="submit">Send message</Button></form>; }
