"use client";

import { Form, FormControl, FormDescription, FormField, FormLabel, FormMessage, FormSubmit } from "@/components/ui/Form";

export function BasicForm() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="email"><FormLabel>Email</FormLabel><FormControl type="email" placeholder="you@example.com" required /><FormMessage match="valueMissing">Please enter your email.</FormMessage></FormField><FormSubmit>Continue</FormSubmit></Form>; }
export function FormWithValidation() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="username"><FormLabel>Username</FormLabel><FormControl pattern="^[a-zA-Z0-9_]+$" required placeholder="joy_ui" /><FormDescription>Letters, numbers, and underscores only.</FormDescription><FormMessage match="valueMissing">A username is required.</FormMessage><FormMessage match="patternMismatch">Use only letters, numbers, and underscores.</FormMessage></FormField><FormSubmit>Save username</FormSubmit></Form>; }
export function FormWithLabel() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="project"><FormLabel>Project name</FormLabel><FormControl placeholder="Joy UI" /><FormDescription>This name will be visible to your team.</FormDescription></FormField><FormSubmit>Create project</FormSubmit></Form>; }
export function FormWithMultipleFields() { return <Form className="w-full max-w-sm space-y-4" onSubmit={(event) => event.preventDefault()}><FormField name="firstName"><FormLabel>First name</FormLabel><FormControl placeholder="Joy" required /></FormField><FormField name="role"><FormLabel>Role</FormLabel><FormControl placeholder="Product designer" required /></FormField><FormSubmit>Update profile</FormSubmit></Form>; }
export function FormWithCustomMessage() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="invite"><FormLabel>Invite code</FormLabel><FormControl placeholder="TEAM-2026" required minLength={8} /><FormMessage match="valueMissing">Invite code is required.</FormMessage><FormMessage match="tooShort">Your invite code is too short.</FormMessage></FormField><FormSubmit>Join workspace</FormSubmit></Form>; }
export function FormWithServerError() { return <Form className="w-full max-w-sm" onSubmit={(event) => event.preventDefault()}><FormField name="account" serverInvalid><FormLabel>Account email</FormLabel><FormControl type="email" defaultValue="taken@example.com" /><FormMessage match="valid" forceMatch>That account is already connected to another workspace.</FormMessage></FormField><FormSubmit>Connect account</FormSubmit></Form>; }
