const shell = (body: string) => `import { Breadcrumb, BreadcrumbCurrent, BreadcrumbEntry, BreadcrumbLink, BreadcrumbList, BreadcrumbSeparator } from "@/components/ui/Breadcrumb";\n\nexport function BreadcrumbExample() {\n  return (${body});\n}`;
export const twoNestedCode = shell(`<Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Components</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Breadcrumb</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>`);
export const threeNestedCode = shell(`<Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Components</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">UI</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Breadcrumb</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>`);
export const customSeparatorCode = shell(`<Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Workspace</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator><span>/</span></BreadcrumbSeparator><BreadcrumbEntry><BreadcrumbCurrent>Settings</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>`);
export const dropdownCode = `"use client";\n\nimport { ChevronDown } from "lucide-react";\nimport { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/DropdownMenu";\nimport { Breadcrumb, BreadcrumbCurrent, BreadcrumbEntry, BreadcrumbLink, BreadcrumbList, BreadcrumbSeparator } from "@/components/ui/Breadcrumb";\n\nexport function DropdownBreadcrumb() {\n  return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Workspace</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><DropdownMenu><DropdownMenuTrigger>Projects <ChevronDown className="size-3" /></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>Design system</DropdownMenuItem><DropdownMenuItem>Marketing site</DropdownMenuItem></DropdownMenuContent></DropdownMenu></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Overview</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>;\n}`;
export const moreOptionsCode = `"use client";\n\nimport { useState } from "react";\nimport { MoreHorizontal } from "lucide-react";\n\nexport function MoreOptionsBreadcrumb() {\n  const [expanded, setExpanded] = useState(false);\n  return <button onClick={() => setExpanded(true)} aria-label="Show more breadcrumb items"><MoreHorizontal /></button>;\n}`;
export const moreOptionsHoverCode = `import { MoreHorizontal } from "lucide-react";\n\nexport function MoreOptionsHoverBreadcrumb() {\n  return <span className="group relative">\n    <button type="button" aria-label="Preview hidden breadcrumb items"><MoreHorizontal /></button>\n    <div className="pointer-events-none absolute opacity-0 transition group-hover:pointer-events-auto group-hover:opacity-100">\n      <a href="#">Components</a>\n      <a href="#">Navigation</a>\n    </div>\n  </span>;\n}`;
export const iconCode = shell(`<Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Home</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Overview</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>`);
export const longCode = shell(`<Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Organization</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">Foundations</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Neutral palette</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>`);
