import { ArrowUpRight, ChevronDown } from "lucide-react";
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, NavigationMenuViewport } from "@/components/ui/NavigationMenu";
const linkClass = "flex min-h-9 items-center rounded-md px-3 py-2 text-sm transition-colors hover:bg-neutral-100 dark:hover:bg-neutral-800";
const dropdownLinkClass = "flex min-h-16 flex-col items-start justify-center rounded-md px-3 py-2 text-left text-sm text-white transition-colors hover:bg-white/10";
export function BasicNavigation() { return <NavigationMenu><NavigationMenuList className="flex gap-1"><NavigationMenuItem><NavigationMenuLink href="#" className={linkClass}>Overview</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#" className={linkClass}>Guides</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#" className={linkClass}>API Reference</NavigationMenuLink></NavigationMenuItem></NavigationMenuList></NavigationMenu>; }
export function NavigationWithDropdown() { return <NavigationMenu className="relative"><NavigationMenuList className="flex gap-1"><NavigationMenuItem><NavigationMenuTrigger>Products <ChevronDown className="ml-1 size-3" /></NavigationMenuTrigger><NavigationMenuContent className="min-h-full border-neutral-700 bg-neutral-900 text-white"><div className="grid gap-2 sm:grid-cols-2"><NavigationMenuLink href="#" className={dropdownLinkClass}><strong>Components</strong><span className="mt-1 block text-xs text-neutral-400">Build with primitives</span></NavigationMenuLink><NavigationMenuLink href="#" className={dropdownLinkClass}><strong>Charts</strong><span className="mt-1 block text-xs text-neutral-400">Make data memorable</span></NavigationMenuLink></div></NavigationMenuContent></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#" className={linkClass}>Pricing</NavigationMenuLink></NavigationMenuItem></NavigationMenuList><NavigationMenuViewport className="bg-neutral-900" /></NavigationMenu>; }
export function NavigationMegaMenu() { return <NavigationMenu className="relative"><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger>Explore</NavigationMenuTrigger><NavigationMenuContent className="border-neutral-200/80 bg-white/75 backdrop-blur-md dark:border-neutral-700/80 dark:bg-neutral-900/75"><div className="grid gap-4 sm:grid-cols-3"><NavigationMenuLink href="#" className={linkClass}>UI Components</NavigationMenuLink><NavigationMenuLink href="#" className={linkClass}>Chart Library</NavigationMenuLink><NavigationMenuLink href="#" className={linkClass}>Creative Lab</NavigationMenuLink></div></NavigationMenuContent></NavigationMenuItem></NavigationMenuList><NavigationMenuViewport /></NavigationMenu>; }
export function NavigationWithBlurredPopup() { return <NavigationMenu className="relative"><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger>Preview</NavigationMenuTrigger><NavigationMenuContent className="border-white/30 bg-neutral-950/65 text-white backdrop-blur-xl"><div className="grid gap-3 sm:grid-cols-2"><NavigationMenuLink href="#" className="flex min-h-16 flex-col items-start justify-center rounded-md px-3 py-2 text-sm text-white transition-colors hover:bg-white/10"><strong>Blurred surface</strong><span className="mt-1 text-xs text-neutral-300">A translucent navigation panel.</span></NavigationMenuLink><NavigationMenuLink href="#" className="flex min-h-16 flex-col items-start justify-center rounded-md px-3 py-2 text-sm text-white transition-colors hover:bg-white/10"><strong>Layered depth</strong><span className="mt-1 text-xs text-neutral-300">Useful over rich page backgrounds.</span></NavigationMenuLink></div></NavigationMenuContent></NavigationMenuItem></NavigationMenuList><NavigationMenuViewport className="bg-neutral-950/65 backdrop-blur-xl" /></NavigationMenu>; }
export function NavigationWithGroups() { return <NavigationMenu className="relative"><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger>Resources</NavigationMenuTrigger><NavigationMenuContent><div className="grid gap-3 sm:grid-cols-2"><div><p className="px-3 text-xs uppercase tracking-wider text-neutral-500">Learn</p><NavigationMenuLink href="#" className={linkClass}>Documentation</NavigationMenuLink><NavigationMenuLink href="#" className={linkClass}>Examples</NavigationMenuLink></div><div><p className="px-3 text-xs uppercase tracking-wider text-neutral-500">Community</p><NavigationMenuLink href="#" className={linkClass}>GitHub <ArrowUpRight className="ml-1 inline size-3" /></NavigationMenuLink><NavigationMenuLink href="#" className={linkClass}>Discussions</NavigationMenuLink></div></div></NavigationMenuContent></NavigationMenuItem></NavigationMenuList><NavigationMenuViewport /></NavigationMenu>; }
export function NavigationWithActiveLink() { return <NavigationMenu><NavigationMenuList className="flex items-center gap-1"><NavigationMenuItem><NavigationMenuLink href="#" className={`${linkClass} bg-neutral-900 text-white hover:bg-neutral-800 dark:bg-white dark:text-black dark:hover:bg-neutral-200`}>Dashboard</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#" className={linkClass}>Activity</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#" className={linkClass}>Settings</NavigationMenuLink></NavigationMenuItem></NavigationMenuList></NavigationMenu>; }
