"use client";

import { useState } from "react";
import { ChevronDown, ChevronRight, Folder, Home, MoreHorizontal } from "lucide-react";
import { Breadcrumb, BreadcrumbCurrent, BreadcrumbEntry, BreadcrumbLink, BreadcrumbList, BreadcrumbSeparator } from "@/components/ui/Breadcrumb";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/DropdownMenu";

export function TwoNestedBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Components</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Breadcrumb</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function ThreeNestedBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Components</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">UI</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Breadcrumb</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function CustomSeparatorBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Workspace</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator><span className="text-neutral-400">/</span></BreadcrumbSeparator><BreadcrumbEntry><BreadcrumbLink href="#">Projects</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator><span className="text-neutral-400">/</span></BreadcrumbSeparator><BreadcrumbEntry><BreadcrumbCurrent>Settings</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function DropdownBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Workspace</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><DropdownMenu><DropdownMenuTrigger className="inline-flex items-center gap-1 font-medium text-neutral-950 dark:text-white">Projects <ChevronDown className="size-3" /></DropdownMenuTrigger><DropdownMenuContent align="start"><DropdownMenuItem>Design system</DropdownMenuItem><DropdownMenuItem>Marketing site</DropdownMenuItem><DropdownMenuItem>Mobile app</DropdownMenuItem></DropdownMenuContent></DropdownMenu></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Overview</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function MoreOptionsBreadcrumb() { const [expanded, setExpanded] = useState(false); return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Home</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator />{expanded ? <><BreadcrumbEntry><BreadcrumbLink href="#">Components</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">Navigation</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /></> : <><BreadcrumbEntry><button type="button" onClick={() => setExpanded(true)} className="inline-flex items-center gap-1 rounded px-1 font-medium text-neutral-950 transition-colors hover:bg-neutral-100 dark:text-white dark:hover:bg-neutral-800" aria-label="Show more breadcrumb items"><MoreHorizontal className="size-4" /><span className="sr-only">Show more</span></button></BreadcrumbEntry><BreadcrumbSeparator /></>}<BreadcrumbEntry><BreadcrumbCurrent>Breadcrumb</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function MoreOptionsHoverBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Home</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry className="group relative"><button type="button" className="inline-flex items-center gap-1 rounded px-1 font-medium text-neutral-950 transition-colors hover:bg-neutral-100 dark:text-white dark:hover:bg-neutral-800" aria-label="Preview hidden breadcrumb items"><MoreHorizontal className="size-4" /><span className="sr-only">Show more</span></button><div className="pointer-events-none absolute left-0 top-full z-10 mt-2 w-52 translate-y-1 rounded-lg border border-neutral-200 bg-white p-2 opacity-0 shadow-xl transition-all duration-200 group-hover:pointer-events-auto group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:pointer-events-auto group-focus-within:translate-y-0 group-focus-within:opacity-100 dark:border-neutral-700 dark:bg-neutral-900"><p className="px-2 pb-1 text-[10px] uppercase tracking-[0.16em] text-neutral-500">Earlier pages</p><div className="space-y-1 text-sm"><BreadcrumbLink href="#" className="block rounded px-2 py-1.5 hover:bg-neutral-100 dark:hover:bg-neutral-800">Components</BreadcrumbLink><BreadcrumbLink href="#" className="block rounded px-2 py-1.5 hover:bg-neutral-100 dark:hover:bg-neutral-800">Navigation</BreadcrumbLink></div></div></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Breadcrumb</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function IconBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#" className="inline-flex items-center gap-1.5"><Home className="size-4" />Home</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#" className="inline-flex items-center gap-1.5"><Folder className="size-4" />Projects</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbCurrent>Overview</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
export function LongBreadcrumb() { return <Breadcrumb><BreadcrumbList><BreadcrumbEntry><BreadcrumbLink href="#">Organization</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">Design system</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">Foundations</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator /><BreadcrumbEntry><BreadcrumbLink href="#">Color</BreadcrumbLink></BreadcrumbEntry><BreadcrumbSeparator><ChevronRight className="size-4" /></BreadcrumbSeparator><BreadcrumbEntry><BreadcrumbCurrent>Neutral palette</BreadcrumbCurrent></BreadcrumbEntry></BreadcrumbList></Breadcrumb>; }
